### ISSUE TITLE
[BUG] stai farm summary return error

### ISSUE THREAD

**Issue by jfikar** [STATION-I/stai-blockchain#24]
I've just updated to the latest version 1.1.2 and now the command `stai farm summary` gives an error. The previous versions were fine.

```

$ stai farm summary
Farming status: Syncing
Total stai farmed: 0.0
User transaction fees: 0.0
Traceback (most recent call last):
  File "/home/pi/stai-blockchain/venv/bin/stai", line 33, in <module>
    sys.exit(load_entry_point('stai-blockchain', 'console_scripts', 'stai')())
  File "/home/pi/stai-blockchain/stai/cmds/stai.py", line 128, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/pi/stai-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/stai-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/stai-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/stai-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/stai-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/stai-blockchain/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/stai-blockchain/stai/cmds/farm.py", line 61, in summary_cmd
    asyncio.run(summary(rpc_port, wallet_rpc_port, harvester_rpc_port, farmer_rpc_port))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/stai-blockchain/stai/cmds/farm_funcs.py", line 217, in summary
    print(f"Block rewards: {(amounts['farmer_reward_amount'] + amounts['officialwallets_reward_amount'] + amounts['pool_reward_amount']) / units['stai']}")
KeyError: 'officialwallets_reward_amount'
```
The `stai version` return 1.1.3.dev2, because I'm using git clone. But I don't think it differs from 1.1.2.

**Comment by guydavis** [comment]
Confirmed.  This is a showstopper for CLI users.

**Comment by mdrodge** [comment]
f

**Comment by STATION-I** [comment]
Bug now fixed with commit #29, update your repository locally to get the changes or delete folder and clone again.
Thanks

**Comment by guydavis** [comment]
Great!  I will make use of the [next released version](https://github.com/STATION-I/stai-blockchain/releases) that contains this fix.  Thanks!

**Comment by jfikar** [comment]
I can confirm, the problem is fixed. Good job!
