### ISSUE TITLE
DB files gets written into directly; no shm, wal files are created, and errors out with database is locked

### ISSUE THREAD

**Issue by priyankub** [STATION-I/stai-blockchain#29]
Stai seems to be directly writing to the database. No shm, and wal files gets created, and after running out for a few hours, stai errors out with the following error:
```
Exception from 'show' Traceback (most recent call last):
  File "/home/pranks/github/chia_forks/stai-blockchain/stai/cmds/show.py", line 123, in show_async
    blockchain_state = await client.get_blockchain_state()
  File "/home/pranks/github/chia_forks/stai-blockchain/stai/rpc/full_node_rpc_client.py", line 32, in get_blockchain_state
    response = await self.fetch("get_blockchain_state", {})
  File "/home/pranks/github/chia_forks/stai-blockchain/stai/rpc/rpc_client.py", line 49, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'database is locked', 'success': False}
```
snippet from database directory:
```
~/.stai/mainnet/db$ ls -lrth
total 18G
-rw------- 1 pranks pranks  74M Mar  5 03:43 height-to-hash
-rw------- 1 pranks pranks 467K Mar  5 03:43 sub-epoch-summaries
-rw-r--r-- 1 pranks pranks  18G Mar  5 14:02 blockchain_v2_mainnet.sqlite
-rw-r--r-- 1 pranks pranks  45K Mar  5 14:02 blockchain_v2_mainnet.sqlite-journal
```
The journal file gets created when the error shows up. Issue is persistent in versions 1.3.0, 1.3.1dev18. Output of lsof:
```
COMMAND       PID   USER   FD   TYPE DEVICE    SIZE/OFF     NODE NAME
stai_full 1671773 pranks    8uw  REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1671773 pranks    9uw  REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1671773 pranks   10uw  REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1671773 pranks   11uw  REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1671773 pranks   12uw  REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672375 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672375 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672375 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672375 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672375 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672377 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672377 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672377 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672377 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672377 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672378 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672378 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672378 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672378 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672378 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672379 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672379 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672379 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672379 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672379 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672380 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672380 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672380 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672380 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672380 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672382 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672382 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672382 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672382 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672382 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672383 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672383 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672383 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672383 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672383 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672384 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672384 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672384 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672384 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672384 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672385 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672385 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672385 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672385 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672385 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672386 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672386 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672386 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672386 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672386 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672387 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672387 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672387 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672387 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672387 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672388 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672388 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672388 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672388 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1672388 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1685044 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1685044 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1685044 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1685044 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1685044 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1685045 pranks    8u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1685045 pranks    9u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1685045 pranks   10u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1685045 pranks   11u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
stai_full 1685045 pranks   12u   REG  252,2 19191214080 21655777 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite
```
lsof for the journal file:
```
COMMAND       PID   USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
stai_full 1671773 pranks   59u   REG  252,2  2902784 27525192 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite-journal
stai_full 1685044 pranks   59u   REG  252,2  2902784 27525192 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite-journal
stai_full 1685045 pranks   59u   REG  252,2  2902784 27525192 /home/pranks/.stai/mainnet/db/blockchain_v2_mainnet.sqlite-journal
```

**Comment by priyankub** [comment]
The root cause seems to be due to the journal_mode not in WAL:
```
sqlite3 ~/.stai/mainnet/db/blockchain_v2_mainnet.sqlite 
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> PRAGMA journal_mode;
delete
```
This could be an isolated incident, and not sure how the journal mode was not set to WAL. The DB was a download from xchguidedb, and the developer has been informed.
After setting journal_mode WAL, things are working fine:
```
sqlite3 ~/.stai/mainnet/db/blockchain_v2_mainnet.sqlite 
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> PRAGMA journal_mode=WAL;
wal
```
wal and shm files are now present:
```
ls -lrth
total 18G
-rw-r--r-- 1 root   root   603K Mar  4 22:17 peers.dat
-rw-r--r-- 1 root   root  18G Mar  6 12:19 blockchain_v2_mainnet.sqlite
-rw-r--r-- 1 root   root    0 Mar  6 12:26 blockchain_v2_mainnet.sqlite-wal
-rw-r--r-- 1 root   root  32K Mar  6 12:26 blockchain_v2_mainnet.sqlite-shm
-rw------- 1 root   root    74M Mar  6 12:26 height-to-hash
-rw------- 1 root   root   468K Mar  6 12:26 sub-epoch-summaries
```

**Comment by WarutaShinken** [comment]
For those who are wondering, xchguidedb.com `VACUUM`s (SQLite command) the databases before making them available for download to reduce their size and improve their performance. This process seems to have the side effect of setting journal mode to `delete` instead of `wal`, so it had to be manually set back to `wal` after vacuuming it.
