### ISSUE TITLE
Client unable to sync or add peers - dead fork?

### ISSUE THREAD

**Issue by ShrektacularSwamp** [STATION-I/stai-blockchain#31]
I have everything set up correctly, it just won't add peers or sync / connect to the network. I have my port properly forwarded.

The discord links everywhere are broken, and there's no twitter activity.

Is this just a dead fork?

**Comment by WarutaShinken** [comment]
Check your logs, are you getting an entry that reads `TypeError: object of type 'NoneType' has no len()`? This issue has recently been reported by other users and I have attempted to fix this under the [null_waiters_quickfix](https://github.com/STATION-I/stai-blockchain/tree/null_waiters_quickfix) branch. If you are installing STAI from source, could you try reinstalling it from this branch?

**Comment by WarutaShinken** [comment]
As for the Discord server invite being broken, I will have to contact a server admin in charge of it to fix that. Here's an alternative invite for now: https://discord.gg/vgf6XUFYnr

**Comment by Yamanipanuchi** [comment]
I installed the branch and ended up with the same error unfortunately.

**Comment by WarutaShinken** [comment]
Are you sure it installed that branch? Please run `git rev-parse --abbrev-ref HEAD` in `stai-blockchain` and make sure it prints `null_waiters_quickfix`. If the error message still shows that the error is happening at line 112 of `full_node_api.py`, it means the branch hasn't been checked out:

```
Traceback (most recent call last):
  File "/.../stai-blockchain/stai/server/server.py", line 605, in wrapped_coroutine
    result = await coroutine
  File "/.../stai-blockchain/stai/full_node/full_node_api.py", line 112, in new_peak
    waiter_count = len(self.full_node.new_peak_sem._waiters)
TypeError: object of type 'NoneType' has no len()
```

**Comment by Yamanipanuchi** [comment]
![image](https://github.com/STATION-I/stai-blockchain/assets/4724631/25103a01-1b38-4bfe-8b8b-c667591ea111)

**Comment by Yamanipanuchi** [comment]
This is what I am getting. I just capture my own node trying to connect to my secondary node.

![image](https://github.com/STATION-I/stai-blockchain/assets/4724631/e8e54b03-5450-4767-88fd-38fa7884874e)

**Comment by WarutaShinken** [comment]
Hmm, that's a pretty useless log entry, it doesn't even tell us the line it happened at.

Anyway, so I made some pushes to `main` that include a more thorough version of `null_waiters_quickfix` (there's another part of the code that's vulnerable to this issue, and I suspect that's why my quickfix didn't work for everyone). Could you pull it and:

* Delete `cache` and `run` under `mainnet`.
* Test it with your current copy of the database.
* If the above doesn't work, test without an existing database.
